### ISSUE TITLE
是否已经可以使用？

### ISSUE THREAD

**Issue by shitou333111** [szuchenjc/vuepress-editor#1]
看起来是很棒的工具，满足我的需求，或许也是很多人的需求。
请问现在是否已经可以测试使用？是否可以先简单写下使用指南？
我 yarn install, 并且yarn dev 之后出现下面界面，点击“打开项目”没有反应，但后台也没有报错终止。
![image](https://github.com/szuchenjc/vuepress-editor/assets/32065299/f45612ec-4443-4105-a90a-263a876fb5c7)

**Comment by szuchenjc** [comment]
@shitou333111 感谢你的关注，看起来你也在寻找一种能便利编辑vuepress文档的方式。本项目其实是桌面端应用，使用tauri框架，并且将在未来支持electron，原理是把vuepress通过工具clone源码到本地后进行工具化管理。目前属于研发初期，打开的vuepress项目也需要是做少量配置的，当然后续会推出一键初始化的功能。

关于你咨询的打开项目的方式，是npm run tauri dev。如何跑tauri框架可以查阅官方文档。未来功能完善后，会完善各项说明。届时可以同步通知你，假设你还需要的话。这个过程可能在1到2个月内。

**Comment by shitou333111** [comment]
> @shitou333111 感谢你的关注，看起来你也在寻找一种能便利编辑vuepress文档的方式。本项目其实是桌面端应用，使用tauri框架，并且将在未来支持electron，原理是把vuepress通过工具clone源码到本地后进行工具化管理。目前属于研发初期，打开的vuepress项目也需要是做少量配置的，当然后续会推出一键初始化的功能。
> 
> 关于你咨询的打开项目的方式，是npm run tauri dev。如何跑tauri框架可以查阅官方文档。未来功能完善后，会完善各项说明。届时可以同步通知你，假设你还需要的话。这个过程可能在1到2个月内。

 感谢回复，持续关注！
